backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

site_url: https://www.sawtooth.dev
display_url: ttps://www.sawtooth.dev
logo_url: https://www.sawtooth.dev/directus/public/uploads/_/originals/fox1.png

show_preview_links: true

collections:
  - name: 'page'
    label: 'Page'
    identifier_field: page_name
    format: 'json'
    folder: 'assets/content/page'
    create: true
    slug: '{{page_name}}'
    editor:
      preview: false
    fields:
      - { label: 'Page Name', name: 'page_name', widget: 'string' }
      - label: "Hero"
        name: "hero"
        widget: "object"
        fields:
        - { label: 'Hero Header', name: 'hero_header', widget: 'string', required: false }
        - { label: 'Hero Para', name: 'hero_para', widget: 'text', required: false }
        - { label: 'Hero Button Text', name: 'hero_button_text', widget: 'string', required: false }
        - { label: 'Hero Button Link', name: 'hero_button_link', widget: 'string', required: false }
        - { label: 'Hero Background Image', name: 'hero_background_image', widget: 'file', required: false }
        - { label: 'Hero Background Video', name: 'hero_background_video', widget: 'file', required: false }
        - { label: 'Hero Sub Image', name: 'hero_sub_image', widget: 'file', required: false }
      - label: "Page Intro"
        name: "page_intro"
        widget: "object"
        fields:
        - { label: 'Page Intro Section Status', name: 'status', widget: 'select', options: ["published", "draft", "deleted"], required: false }
        - { label: 'Page Intro Header', name: 'page_intro_header', widget: 'string', required: false }
        - { label: 'Page Intro Para', name: 'page_intro_para', widget: 'text', required: false }
      - label: "Page Section - 1"
        name: "page_section_1"
        widget: "object"
        fields:
        - { label: 'Page Section 1 Status', name: 'status', widget: 'select', options: ["published", "draft", "deleted"], required: false }
        - { label: 'Page Section 1 Header', name: 'page_section_1_header', widget: 'string', required: false }
        - { label: 'Page Section 1 Para', name: 'page_section_1_para', widget: 'text', required: false}
      - label: "Page Section - 2"
        name: "page_section_2"
        widget: "object"
        fields:
        - { label: 'Page Section 2 Status', name: 'status', widget: 'select', options: ["published", "draft", "deleted"], required: false }
        - { label: 'Page Section 2 Header', name: 'page_section_2_header', widget: 'string', required: false }
        - { label: 'Page Section 2 Para', name: 'page_section_2_para', widget: 'text', required: false }
      - label: "Page Section - 3"
        name: "page_section_3"
        widget: "object"
        fields:
        - { label: 'Page Section 3 Status', name: 'status', widget: 'select', options: ["published", "draft", "deleted"], required: false }
        - { label: 'Page Section 3 Header', name: 'page_section_3_header', widget: 'string', required: false }
        - { label: 'Page Section 3 Para', name: 'page_section_3_para', widget: 'text', required: false }
      - label: "Page Section - 4"
        name: "page_section_4"
        widget: "object"
        fields:
        - { label: 'Page Section 4 Status', name: 'status', widget: 'select', options: ["published", "draft", "deleted"], required: false }
        - { label: 'Page Section 4 Header', name: 'page_section_4_header', widget: 'string', required: false }
        - { label: 'Page Section 4 Para', name: 'page_section_4_para', widget: 'text', required: false }
      - label: "Page Section - 5"
        name: "page_section_5"
        widget: "object"
        fields:
        - { label: 'Page Section 5 Status', name: 'status', widget: 'select', options: ["published", "draft", "deleted"], required: false }
        - { label: 'Page Section 5 Header', name: 'page_section_5_header', widget: 'string', required: false }
        - { label: 'Page Section 5 Para', name: 'page_section_5_para', widget: 'text', required: false }

  - name: 'nav'
    label: 'Nav Items'
    identifier_field: nav_title
    format: 'json'
    folder: 'assets/content/nav'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Nav Item Status', name: 'status', widget: 'select', options: ["published", "draft", "deleted"], required: false }
      - label: "Sort Number"
        name: "sort_number"
        widget: "number"
        default: 1
        valueType: "int"
        min: 1
        max: 14
      - { label: 'Nav Title', name: 'nav_title', widget: 'string', required: false }
      - { label: 'Nav Para', name: 'nav_para', widget: 'text', required: false }
      - { label: 'Nav Link', name: 'nav_link', widget: 'string', required: false }
      - { label: 'Nav Icon', name: 'nav_icon', widget: 'file', required: false }

  - name: 'sitewide'
    label: 'Sitewide'
    identifier_field: company_name
    format: 'json'
    folder: 'assets/content/sitewide'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Company Name', name: 'company_name', widget: 'string' }
      - { label: 'Company Logo', name: 'company_logo', widget: 'file', required: false }
      - { label: 'Company Address Line 1', name: 'company_address_line_1', widget: 'string', required: false }
      - { label: 'Company Address Line 2', name: 'company_address_line_2', widget: 'string', required: false }
      - { label: 'Company Address Line 3', name: 'company_address_line_3', widget: 'string', required: false }
      - { label: 'Company Phone Number', name: 'company_phone_number', widget: 'string', required: false }
      - { label: 'Company Email Address', name: 'company_email_address', widget: 'string', required: false }
      - label: "Contact Box - Every Page"
        name: "contact_box"
        widget: "object"
        fields:
        - { label: 'Contact Header', name: 'contact_header', widget: 'string', required: false }
        - { label: 'Contact Para', name: 'contact_para', widget: 'text', required: false }
        - { label: 'Contact Button Link', name: 'contact_button_link', widget: 'string', required: false }
        - { label: 'Contact Button Text', name: 'contact_button_text', widget: 'string', required: false }
      - label: "Footer Details"
        name: "footer_details"
        widget: "object"
        fields:
        - { label: 'Footer - Show Site Links', name: 'footer_show_site_links', widget: 'boolean', required: false }
        - { label: 'Footer Company Para', name: 'footer_company_para', widget: 'text', required: false }
        - { label: 'Footer Copyright', name: 'footer_copyright', widget: 'string', required: false }
      - label: "Social Media"
        name: "social_media"
        widget: "object"
        fields:
        - { label: 'Footer - Show Social Media', name: 'footer_show_social', widget: 'boolean', required: false }
        - { label: 'Facebook Link', name: 'facebook_link', widget: 'string', required: false }
        - { label: 'Instagram Link', name: 'instagram_link', widget: 'string', required: false }
        - { label: 'Twitter Link', name: 'twitter_link', widget: 'string', required: false }
        - { label: 'GitHub Link', name: 'github_link', widget: 'string', required: false }
        - { label: 'Dribble Link', name: 'dribble_link', widget: 'string', required: false }

  - name: 'services'
    label: 'Services'
    identifier_field: service_type
    format: 'json'
    folder: 'assets/content/services'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Service Status', name: 'status', widget: 'select', options: ["published", "draft", "deleted"], required: false }
      - { label: 'Service Type', name: 'service_type', widget: 'string' }
      - label: "Sort Number"
        name: "sort_number"
        widget: "number"
        default: 1
        valueType: "int"
        min: 1
        max: 20
        required: false
      - { label: 'Service Short Description', name: 'service_short_description', widget: 'text', required: false }
      - { label: 'Service Icon', name: 'service_icon', widget: 'file', required: false }
      - { label: 'Service Link', name: 'service_link', widget: 'text', required: false }

  - name: 'process'
    label: 'Process'
    identifier_field: process_header
    format: 'json'
    folder: 'assets/content/process'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Process Status', name: 'status', widget: 'select', options: ["published", "draft", "deleted"], required: false }
      - label: "Sort Number"
        name: "sort_number"
        widget: "number"
        default: 1
        valueType: "int"
        min: 1
        max: 20
        required: false
      - { label: 'Process Header', name: 'process_header', widget: 'string', required: false }
      - { label: 'Process Short Description', name: 'process_short_description', widget: 'text', required: false }

  - name: 'testimonials'
    label: 'Testimonials'
    identifier_field: name
    format: 'json'
    folder: 'assets/content/testimonials'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Testamonial Status', name: 'status', widget: 'select', options: ["published", "draft", "deleted"], required: false }
      - label: "Sort Number"
        name: "sort_number"
        widget: "number"
        default: 1
        valueType: "int"
        min: 1
        max: 20
        required: false
      - { label: 'Testamonial Name', name: 'name', widget: 'string', required: false }
      - { label: 'Testamonial Text', name: 'text', widget: 'text', required: false }
      - { label: 'Testamonial Description', name: 'string', widget: 'text', required: false }

  - name: 'privacy_policy'
    label: 'Privacy Policy'
    identifier_field: privacy_policy_name
    format: 'json'
    folder: 'assets/content/privacy-policy'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Privacy Policy Unique Name', name: 'privacy_policy_name', widget: 'string', required: false }
      - { label: 'Privacy Policy Text', name: 'privacy_policy_text', widget: 'markdown', required: false, buttons: ["bold", "italic", "link", "heading-two", "bulleted-list", "numbered-list"] }
